# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="PERLANCAR"
MODULE_VERSION="0.140"


inherit perl-module

DESCRIPTION="Send logs to screen, with colors and some other features"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Log-Any-1.701.0
	dev-lang/perl"
