# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="CLKAO"
MODULE_VERSION="0.32"


inherit perl-module

DESCRIPTION="test log4perl"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Log-Log4perl
	dev-perl/Test-Exception
	dev-lang/perl"
