# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="LARRYSH"
MODULE_VERSION="0.12"


inherit perl-module

DESCRIPTION="Perl extension defining ranges of numbers and testing if a number is found in the range. You can also add and delete from this range."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-lang/perl"
