# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=7

DIST_AUTHOR="MSCHWERN"
DIST_VERSION="v${PV}"

inherit perl-module

DESCRIPTION="A unique identifier for any object"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Module-Build-0.422.400
	>=dev-perl/Sub-Name-0.50.0
	>=dev-perl/Hash-FieldHash-0.150.0
	dev-lang/perl"
